In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from dateutil.parser import parse
from datetime import date

In [2]:
df=pd.read_csv('../data다운로드파일/인천광역시_반려동물 보유 및 등록 현황_20191231.csv', encoding='MS949')

In [3]:
df1=pd.read_csv('../data다운로드파일/반려동물등록현황.csv', encoding='MS949')

In [4]:
df

,구,개 보유 여부 (%),고양이 보유 여부 (%),기타 보유 여부 (%),반려동물 없음 (%),개 보유 수(평균) (마리),고양이 보유 수(평균) (마리),기타 보유 수(평균) (마리),반려견 등록 (%),반려견 미등록 (%)
0,동구,83.6,16.5,1.0,86.1,1.2,1.5,4.0,66.1,33.9
1,미추홀구,90.1,12.2,4.0,87.5,1.2,1.5,2.0,48.8,51.2
2,연수구,78.3,17.3,6.9,87.7,1.2,1.6,1.7,52.0,48.0
3,남동구,83.8,18.9,6.2,84.6,1.3,1.6,1.6,68.2,31.8
4,부평구,76.1,17.5,9.3,84.8,1.3,1.8,2.4,76.1,23.9
5,계양구,78.5,22.5,3.1,85.6,1.1,1.5,2.4,58.3,41.7
6,서구,76.5,20.1,7.9,81.6,1.2,1.6,2.0,61.8,38.2
7,강화군,92.4,18.0,2.9,76.6,1.6,2.2,2.8,16.1,83.9
8,옹진군,79.0,36.4,3.4,74.2,1.7,2.4,13.4,15.1,84.9

In [7]:
df1

,시군명,읍면동명,등록동물수(마리),(등록주체)시군구등록,(등록주체)대행업체등록,(등록주체)기타,(RFID종류)내장형,(RFID종류)외장형,(RFID종류)인식표,등록품종수,등록소유자수,동물소유자당등록동물수,해당동의등록대행업체수,데이터기준일자
0,가평군,가평읍,941,NaN,NaN,NaN,596,294,51,NaN,85.0,NaN,3.0,2022-06-14
1,가평군,북면,289,NaN,NaN,NaN,176,93,20,NaN,185.0,NaN,0.0,2022-06-14
2,가평군,상면,399,NaN,NaN,NaN,217,153,29,NaN,243.0,NaN,0.0,2022-06-14
3,가평군,설악면,1111,NaN,NaN,NaN,446,612,53,NaN,625.0,NaN,1.0,2022-06-14
4,가평군,조종면,416,NaN,NaN,NaN,218,161,37,NaN,274.0,NaN,1.0,2022-06-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,화성시,청계동,2046,90.0,1956.0,0.0,1052,879,115,66.0,1679.0,1.22,4.0,2022-05-31
733,화성시,팔탄면,753,87.0,665.0,1.0,345,305,103,62.0,412.0,1.83,1.0,2022-05-31
734,화성시,향남읍,5180,314.0,4863.0,3.0,2110,2584,486,103.0,3719.0,1.39,6.0,2022-05-31
735,화성시,활초동,15,0.0,15.0,0.0,4,11,0,7.0,11.0,1.36,0.0,2022-05-31
736,화성시,황계동,52,16.0,36.0,0.0,19,13,20,15.0,24.0,2.17,0.0,2022-05-31

In [8]:
df1['시군명'].value_counts()

수원시     55
고양시     53
화성시     52
성남시     46
안성시     46
평택시     38
용인시     36
파주시     35
여주시     32
안산시     31
시흥시     30
이천시     25
부천시     25
오산시     24
하남시     23
양주시     22
광주시     22
포천시     18
남양주시    16
김포시     15
동두천시    12
양평군     12
의왕시     11
과천시     10
연천군     10
군포시      9
광명시      8
구리시      7
안양시      7
가평군      6
의정부시     1
Name: 시군명, dtype: int64